versions:
  - "8.2"
  - "8.3"
  - "8.4"
  - "8.5"

extensions: "all"

platforms:
  - os: linux
    arch: x86_64
  - os: linux
    arch: aarch64
  - os: darwin
    arch: x86_64
  - os: darwin
    arch: aarch64
